### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by nathanaelytj** [laracasts/Laravel-5-Generators-Extended#160]
This is just a question. Is this project still maintained? At the moment of this comment, Laravel already at version 5.7

**Comment by tabacitu** [comment]
Hi @nathanaelytj ,

Jeffrey himself hasn't pushed any updates to this project in a while, no. A while back he gave me ```write``` access, because we use it in [Backpack for Laravel](https://backpackforlaravel.com), but we don't _need_ or _plan_ to add any features to it - just keep it working.

Right now, it IS working on 5.7 - I've used it myself.

Cheers!

**Comment by amberlampsio** [comment]
> Hi @nathanaelytj ,
> 
> Jeffrey himself hasn't pushed any updates to this project in a while, no. A while back he gave me `write` access, because we use it in [Backpack for Laravel](https://backpackforlaravel.com), but we don't _need_ or _plan_ to add any features to it - just keep it working.
> 
> Right now, it IS working on 5.7 - I've used it myself.
> 
> Cheers!

Please cut a new release!

**Comment by tabacitu** [comment]
I've just pushed support for Laravel 7, a few hours after launch. 
So I'd say yes, it is maintained 😁  Not very well. But maintained 😆
