### ISSUE TITLE
Pivot generator sometimes sorts columns wrong

### ISSUE THREAD

**Issue by Data33** [laracasts/Laravel-5-Generators-Extended#39]
In edge cases like when two table names overlap, the pivot generator will sort them wrong.

For example: Two tables, students and studentgroups will be sorted as studentgroup_student instead of student_studentgroup.

Suggested fix:
In PivotMigrationMakeCommand.php make sure to re-sort table names after applying str_singular on them.

I would submit a patch but I'm new to git and github, so sorry :/

**Comment by tabacitu** [comment]
Hi @Data33 - I know this is an old issue, but it sounded like a good idea. Maybe you have more experience with git and github now and can submit a PR.

Since the issue is old, and the edge case doesn't seem very common(nobody jumped on the bandwagon in 5 years), I'm going to close this. Would merge a PR that does this, though.

Cheers!
