### ISSUE TITLE
2 migrations files are generated on  php artisan make:migration:schema.

### ISSUE THREAD

**Issue by ghost** [laracasts/Laravel-5-Generators-Extended#40]
``` 
php artisan make:migration:schema create_companies_table - schema="user_id:integer:foreign:unsign
ption:text,active:boolean,tax_no:varchar,child:boolean,child_of:integer:unsign"
```

This command generate two files ,

2015_05_13_084536_create_companies_table

```php
public function up()
{
    Schema::create('companies', function(Blueprint $table) {
        $table->increments('id');
        $table->integer('user_id')->unsigned();
        $table->foreign('user_id')->references('id')->on('users');
        $table->string('title');
        $table->text('description');
        $table->boolean('active');
        $table->varchar('tax_no');
        $table->boolean('child');
        $table->intger('child_of')->unsign();
        $table->timestamps();
    });
}
```

2015_05_13_084537_create_companies_table

```php
public function up()
{
    Schema::create('companies', function(Blueprint $table)
    {
        $table->increments('id');
        $table->timestamps();
    });
}
```

And in autoload class it register first migration file.
'CreateCompaniesTable' => $baseDir . '/database/migrations/2015_05_13_084536_create_companies_table.php',

**Comment by rodelapena** [comment]
i have the same problem, please help.
here ii is:

rodrigo@jarvis:~/Projects/asistencia > php artisan make:migration:schema create_managers_table --schema="username:string, email:string:unique"
Migration created successfully.
Model created successfully.
Created Migration: 2015_05_13_224930_create_managers_table

two migration files are created:
2015_05_13_224929_create_managers_table.php
<?php

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateManagersTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('managers', function(Blueprint $table) {
            $table->increments('id');
            $table->string('username');
            $table->string('email')->unique();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::drop('managers');
    }
}



and:
2015_05_13_224930_create_managers_table.php
<?php

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateManagersTable extends Migration {

	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		Schema::create('managers', function(Blueprint $table)
		{
			$table->increments('id');
			$table->timestamps();
		});
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::drop('managers');
	}

}


here is my info:

rodrigo@jarvis:~/Projects/asistencia > php artisan
Laravel Framework version 5.0.31


rodrigo@jarvis:~/Projects/asistencia > php -v
PHP 5.5.9-1ubuntu4.9 (cli) (built: Apr 17 2015 11:44:57) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies


composer require laracasts/generators --dev

rodrigo@jarvis:~/Projects/asistencia > mysql -V
mysql  Ver 15.1 Distrib 5.5.41-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2


thank you!

**Comment by odin88** [comment]
+1 same problem to me as well

**Comment by joarobles** [comment]
+1 same problem to me as well after upgrade from 1.1 to 1.1.1

**Comment by AngelinDark** [comment]
+1 the same for me

**Comment by woodytang** [comment]
same here!

**Comment by ubunifu** [comment]
+1 same problem
first go creating default
**php artisan make:migration**:schema **create_posts_table** --schema="user_id:integer:foreign, title:string,body:text"
and after script work as well and create his own migration

**Comment by Elyahou** [comment]
+1 here

**Comment by ubunifu** [comment]
I do not understand why, but I dont have this problem more)

**Comment by dojorob76** [comment]
+1 -although, oddly, it doesn't happen about 1% of the time...

**Comment by arifmahmudrana** [comment]
same here

**Comment by erenMustafaOzdal** [comment]
same here. **Please help!** :)

**Comment by lmatab** [comment]
Same  Here!, Hey  Jeff  where are you?

**Comment by cantecim** [comment]
Sometimes it doesn't happen only we get migration that trash one. Its even worse now in my case

**Comment by lmatab** [comment]
yes it  happens, I guess  it is a bug, I always  keep and eye  on the  files generated so I can delete  the  ones that  are not  necessary!

**Comment by azamuddin** [comment]
same here

**Comment by bebnev** [comment]
`make:migration:schema` is using Laravel `make:model` command for model generation.
And by default `make:migration:schema` will generate model class (if it does not exist).
If you are using `laravel/framework 5.0.*` `make:model` by default will generate the migration.
So calling `make:migration:schema` generates the migration, then calls `make:model` which generates Model and migration (again). So that is the point.
`laravel/framework 5.1.*` `make:model` command by default will not generate the migration file, so updating laravel will solve the problem.
Or if you don't want to update just call `make:migration:schema` with option `--model=false`, and generate model by your hands or with laravel `make:model` command with option `--no-migration`

**Comment by bebnev** [comment]
`make:migration:schema` is using Laravel `make:model` command for model generation.
And by default `make:migration:schema` will generate model class (if it does not exist).
If you are using `laravel/framework 5.0.*` `make:model` by default will generate the migration.
So calling `make:migration:schema` generates the migration, then calls `make:model` which generates Model and migration (again). So that is the point.
`laravel/framework 5.1.*` `make:model` command by default will not generate the migration file, so updating laravel will solve the problem.
Or if you don't want to update just call `make:migration:schema` with option `--model=0` (because `--model=false` doesn't work #41), and generate model by your hands or with laravel `make:model` command with option `--no-migration`

**Comment by tabacitu** [comment]
I know this is a very old issue, but @bebnev thank you for helping people out on this! Closing since it's no longer the case - in v2 we're dropping support for Laravel 5.0 https://github.com/laracasts/Laravel-5-Generators-Extended/pull/170
