### ISSUE TITLE
Creating Migrations From a Controller

### ISSUE THREAD

**Issue by tnagengast** [laracasts/Laravel-5-Generators-Extended#57]
Any suggestions on creating migrations from a controller? 

When running 

``` php
Artisan::call('make:migration:schema', ['name' => 'create_test_table', '--schema' => 'username:string, email:string:unique']);
```

 no migration is created.

**Comment by tnagengast** [comment]
I found by using ```'name' => 'create_test_table'``` it would create the model but the migration is still not being created.

**Comment by tnagengast** [comment]
Realized I need to use ```'name' => 'create_test_table'```

**Comment by b3zman41** [comment]
I found out what the bug is. It's because in the source of the MigrationMakeCommand, he uses a relative path :

`return '/migrations/' . date('Y_m_d_His') . '_' . $name . '.php';`

 when it should use Laravel's helpers :

 `return database_path() . '/migrations/' . date('Y_m_d_His') . '_' . $name . '.php';`

**Comment by tnagengast** [comment]
Great spot!! Works like a charm, thank you :)

**Comment by tabacitu** [comment]
Hi guys. I see we're using ```base_path() . '/database/migrations/' . date('Y_m_d_His') . '_' . $name . '.php';``` now so I assume this has been fixed somewhere between 2015 and 2020 😄 

So I'll close the issue. Let me know if it's not the case and we'll reopen.

Cheers!
